---
- name: Using EOS specific module to run commands
  hosts: arista_switches
  gather_facts: false
  connection: network_cli    # required for ansible to use CLI over SSH 
  become: yes                # run with privledge
  become_method: enable      # use in place of "sudo"

  vars:
          ansible_ssh_pass: alta3

  tasks:
          - name: Run Multiple commands on remote devices
            arista.eos.eos_command:
                    commands:
                            - show version
                            - show interfaces

            register: show_output


          - name: Take a peak at the "show output"
            debug:
                    var: show_output 
