---
- name: Playbook with the register keyword
  hosts: planet_express


  tasks:
          - name: "Issue a trivial command"
            command: ls /lib/
            register: contentz_lib

          - name: "Debug - display data returned"
            debug: 
                msg: "{{ contentz_lib }}"

          - name: "Debug - Standard error"
            debug:
                    msg: "{{ contentz_lib.stderr }}"

          - name: "Debug - Standard out"
            debug:
                    msg: "{{ contentz_lib.stdout }}"

