---
- name: Exploring the template modules and jinja expressions
  hosts: planetexpress
  gather_facts: false # runs the 'setup' module on remote hosts

  # these variable are used in template ship.cfg.j2
  vars:
          ship_name: Bessie
          ship_type: Intergalatic
          engines: Dark Matter
          dark_matter_balls: 63
          backup_engines: Chemical


  tasks:
          - name: Configure spaceship registration
            template:
                    src: templates/ship.cfg.j2 # Name of the template on ansible controller
                    dest: ~/ship.cfg           # Name of the completed file to be placed on the target system
